name: PlayerSizer
version: 1.2.0
author: [Matthww, robske_110]
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9]
description: Resizes a certain player.
main: Matthww\PlayerSizer\PlayerSizer

commands:
 size:
  description: Sets the size of a player!
  usage: "/size <player> <size>"
  permission: playersizer.use
  aliases: ['scale']
permissions:
  size:
    default: false
    children:
      playersizer.use:
        default: op
        description: "Allows the user to run the size command and resize himself"
      playersizer.other:
        default: op
        description: "Allows the user to resize other players"
